1747593683779	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747593686671	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1747593686671	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747593686672	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1747593686675	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1747593691384	Sync.Service	DEBUG	User-Agent: Firefox/138.0.4 (Linux x86_64) FxSync/1.140.0.20250518015817.desktop
1747593691384	Sync.Service	INFO	Starting sync at 2025-05-19 00:11:31 in browser session VIiW7KW0WK6-
1747593691384	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1747593691387	Sync.Status	INFO	Resetting Status.
1747593691387	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1747593691387	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1747593691389	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/195504406/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747593691389	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1747593691389	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1747593691389	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1747593691390	Sync.SyncScheduler	DEBUG	Next sync in 90000 ms. (why=reschedule)
1747593691391	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
